### ISSUE TITLE
how to solve You must have either emcc or docker on your PATH to run this command

### ISSUE THREAD

**Issue by LanHuangJG** [curlconverter/curlconverter.github.io#92]
![image](https://github.com/curlconverter/curlconverter.github.io/assets/125177842/08996edf-0131-4d23-8089-4a83fd2b48db)
this error happened when i run npm install

**Comment by cf512** [comment]
See the readme.

**Comment by verhovsky** [comment]
Follow the installation instructions at https://emscripten.org/docs/getting_started/downloads.html or install docker https://docs.docker.com/desktop/install/windows-install/
